# Generated by Django 5.2.6 on 2025-11-29 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_year', models.IntegerField(default=0, verbose_name='Год рождения')),
                ('birth_month', models.IntegerField(default=0, verbose_name='Месяц рождения')),
                ('birth_day', models.IntegerField(default=0, verbose_name='День рождения')),
                ('circle', models.IntegerField(choices=[(1, 'Развития'), (2, 'Продуктивности'), (3, 'Поддержки')], default=1, verbose_name='Круг')),
                ('sex', models.IntegerField(choices=[(1, 'Неизвестно'), (2, 'Мужчина'), (3, 'Женщина')], default=1, verbose_name='Пол')),
                ('closing', models.IntegerField(default=0, verbose_name='Близость')),
                ('book_contact_type', models.IntegerField(choices=[(1, 'Не указано'), (2, 'Коннектор'), (3, 'Конденсатор'), (4, 'Мост')], default=1, verbose_name='Тип контакта')),
                ('book_did', models.IntegerField(choices=[(1, 'Не указано'), (2, 'Опасен'), (3, 'Интересен'), (4, 'Сложен')], default=1, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='HumanRelationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, verbose_name='Значение')),
                ('status', models.IntegerField(choices=[(1, 'Активен'), (2, 'Неактивен'), (3, 'Удалён аккаунт')], default=1, verbose_name='Статус')),
                ('data', models.JSONField(default=dict)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.contacttype')),
            ],
        ),
        migrations.CreateModel(
            name='LinkContactCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.community')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.contact')),
            ],
        ),
        migrations.CreateModel(
            name='LinkContactHuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.contact')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.human')),
            ],
        ),
        migrations.CreateModel(
            name='LinkHumanCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.community')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.human')),
            ],
        ),
        migrations.CreateModel(
            name='LinkHumanHuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.human')),
                ('human_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humans_linked', to='db.human')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.humanrelationtype')),
            ],
        ),
        migrations.CreateModel(
            name='LinkHumanMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.human')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.meeting')),
            ],
        ),
        migrations.AddField(
            model_name='human',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humans', to='db.sector'),
        ),
        migrations.CreateModel(
            name='LinkTaskMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.meeting')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.task')),
            ],
        ),
        migrations.CreateModel(
            name='LinkTaskHuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.human')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.task')),
            ],
        ),
        migrations.CreateModel(
            name='LinkTaskCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.community')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.task')),
            ],
        ),
    ]
