# Generated by Django 5.2.1 on 2026-06-10 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='contacttype',
            options={'verbose_name': 'Тип контакта', 'verbose_name_plural': 'Типы контактов'},
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='humanrelationtype',
            options={'verbose_name': 'Тип отношений', 'verbose_name_plural': 'Типы отношений'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': 'Встреча', 'verbose_name_plural': 'Встречи'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Сектор', 'verbose_name_plural': 'Секторы'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskaim',
            options={'verbose_name': 'Цель задачи', 'verbose_name_plural': 'Цели задачи'},
        ),
        migrations.AddField(
            model_name='human',
            name='notes',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='human',
            name='book_did',
            field=models.IntegerField(choices=[(1, 'Не указано'), (2, 'Опасен'), (3, 'Интересен'), (4, 'Сложен')], default=1, verbose_name='Анализ ОИС'),
        ),
        migrations.AlterField(
            model_name='human',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humans', to='db.sector', verbose_name='Сектор'),
        ),
    ]
