# Generated by Django 5.2.1 on 2026-07-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('db', '0002_alter_community_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(related_name='communities', to='common.tag'),
        ),
        migrations.AddField(
            model_name='human',
            name='tags',
            field=models.ManyToManyField(related_name='humans', to='common.tag'),
        ),
    ]
