# Generated by Django 5.2.1 on 2026-08-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('db', '0003_community_tags_human_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tags',
            field=models.ManyToManyField(related_name='communities', to='base.tag'),
        ),
        migrations.AlterField(
            model_name='human',
            name='tags',
            field=models.ManyToManyField(related_name='humans', to='base.tag'),
        ),
    ]
